FROM python:3.12-slim

RUN pip install --no-cache-dir qdrant-client openai python-dotenv

ARG CHUNKS_URL=https://waivatar.s3.us-east-1.amazonaws.com/avatar_chunks.jsonl
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/* \
    && mkdir -p /data \
    && mkdir -p /app \
    && curl -L $CHUNKS_URL -o /app/avatar_chunks.jsonl

COPY data/embed_data.py /app/embed_data.py
WORKDIR /app

CMD ["python", "embed_data.py"]
