apiVersion: v1
kind: Secret
metadata:
  name: {{ include "waivatar.fullname" . }}-secret
type: Opaque
data:
  openaiApiKey: {{ .Values.secrets.openaiApiKey | b64enc | quote }}
  qdrantApiKey: {{ .Values.secrets.qdrantApiKey | b64enc | quote }}
